### ISSUE TITLE
Support geospatial commands

### ISSUE THREAD

**Issue by penso** [sds/mock_redis#130]
Redis 3.2 added geo methods like `geoadd` or `georadius`. Of course I now get:

```
undefined method `geoadd' for #<MockRedis::Database:0x000000138e33d0>
```

Any plan to add those methods listed at https://redis.io/commands/geoadd ?

**Comment by sds** [comment]
Hey @penso! 

Didn't realize this landed in 3.2. Awesome!

I don't think anyone will have bandwidth to look into this anytime soon. Would be more than happy to accept a pull request adding geospatial support, though!

**Comment by dezmaeth** [comment]
Was this implemented?

**Comment by sds** [comment]
@dezmaeth No, but happy to merge a pull request adding support!

**Comment by rkotov93** [comment]
Hey @sds,

I would happy to implement this methods, but there is one thing to discuss. [In the documentation](https://redis.io/commands/geoadd#how-does-it-work) to `GEOADD` method is said that Geohash algorithm is used to populate sorted set. There is a gem that calculates Geohash called (unexpectedly) [geohash](https://github.com/davetroy/geohash). What do you think of adding it as a dependency? Or you prefer to do smth like here at https://github.com/brigade/mock_redis/issues/135?

**Comment by sds** [comment]
Hey @rkotov93, would be happy to merge a pull request. Yes, it would be preferable to to not include `geohash` as a required dependency to use `mock_redis`.

I'm not sure why a separate gem was created in #135—all I ask is that we not add the gem dependencies to the gemspec and instead add them to the `Gemfile` (this allows us to test/develop these extensions, but doesn't require users of the gem to install them). 

As long as installation is optional I think we'll be in a good place. Thanks!

**Comment by rkotov93** [comment]
@sds forgot to let you know that I started working on this issue and already have `geoadd` implemented and tested

**Comment by rkotov93** [comment]
`geoadd`, `geodist`, `geohash` and `geopos` are implemented and tested already. `georadius` and `georadiusbymember` are left 👌

**Comment by rkotov93** [comment]
Hey @sds, I decided to submit a pull request with implementation of that 4 geospatial methods first and then add `georaius` and `georadiusbymember`, because these two methods require a lot of coding and probably some refactoring, that will make the PR really huge and complicated to review and also take a lot of time.

**Comment by srbaker** [comment]
This dumb implementation of `georadius` is working for me:

```
    def georadius(key, longitude, latitude, radius, unit)
      to_meter = parse_unit(unit)

      zrange(key, 0, -1).select do |id|
        location = geopos(key, id)
        distance = geohash_distance(longitude, latitude,
                                    location[0][0].to_f, location[0][1].to_f) / to_meter
        distance < radius
      end
    end
```

**Comment by sds** [comment]
I'm going to close this issue due to age, but if anyone is interested in seeing additional geospatial commands implemented, pull requests are more than welcome!
