### ISSUE TITLE
Supporting eval

### ISSUE THREAD

**Issue by polpak** [sds/mock_redis#135]
Any interest in adding support for eval (and possibly evalsha) using embedded LUA? I'm looking at the  rufus-lua gem and it seems as though it wouldn't be difficult to wire up, but would require additional dependencies. If there is interest, how would you prefer that was tied in?

**Comment by sds** [comment]
Hey @polpak,

Happy to merge a pull request adding support. However, since including the `rufus-lua` gem for all users is a bit much, I would suggest we simply document it as an optional dependency to be included in your Gemfile only if you require Lua support. Does that seem reasonable?

**Comment by polpak** [comment]
Agreed about the needless dependency for some users. I started a project at work to solve this. The gem is here if you're interested in incorporating it.

https://github.com/Invoca/mock_redis_lua_extension
