### ISSUE TITLE
Streams support

### ISSUE THREAD

**Issue by jrmhaig** [sds/mock_redis#141]
Is there a plan to support Redis Streams (see https://redis.io/topics/streams-intro)? This feature will only become available with Redis 5.0 and as this is currently in beta I can understand that there is no reason it should be available. However, with a server running 4.9.101 (the release candidate) I can use (for example):

    require 'redis'
    redis.xadd 'mystream', '*', 'sensor-id', 1234, 'temperature', 19.8
    # => entry ID returned as a string

I am currently evaluating Redis Streams and, if I go ahead with using them, I may try to create a wrapper gem. `mock_redis` would be very helpful for unit tests.

**Comment by jrmhaig** [comment]
And I see that the README has 'The current implementation is tested against Redis 4' so there is no reason at all why Streams should be available yet. I'd still be interested to know, though. :-)

**Comment by sds** [comment]
We have no explicit plans to support streams. Would happily merge a pull request adding support, however. 😄

**Comment by jrmhaig** [comment]
Thanks. I'm not promising anything but I have started looking at implementing this here: https://github.com/jrmhaig/mock_redis

One slight problem I have is that the ids assigned to the stream items are based on the current time in milliseconds and this means that [one of my tests](https://github.com/jrmhaig/mock_redis/blob/master/spec/commands/xadd_spec.rb#L6-L9) occasionally fails because the id created by the real Redis server differs from the one created by MockRedis by one millisecond. Is there a way to make the comparison done by RSpec a little less strict?

Also, before I go too far down this route do you have any comments regarding naming conventions or anything else?

**Comment by sds** [comment]
Rather than test that the ID matches the timestamp, would it make sense to instead test that the ID is always monotonically increasing?

Otherwise you'll necessarily have to construct the test to give yourself some wiggle room for checking the ID.

**Comment by jrmhaig** [comment]
The problem isn't with the test itself but rather with the comparison that is done before with the real Redis server.

**Comment by sds** [comment]
In that case I unfortunately don't have a good workaround to suggest.

**Comment by sds** [comment]
Thanks for your work on this in #142 and #156, @jrmhaig.
