### ISSUE TITLE
dump/restore

### ISSUE THREAD

**Issue by jdelStrother** [sds/mock_redis#175]
Hi there - would you be interested in a pull request that used Marshal.dump to implement `redis.dump` & `redis.restore` ?  It would mean the resulting value from `MockRedis#dump` wouldn't be compatible with a real `Redis#dump`, but it would allow you to call dump/restore to transport data between two MockRedis instances.

**Comment by sds** [comment]
Thanks for the suggestion. Happy to accept a pull request with tests!

**Comment by sds** [comment]
Implemented in #176. Thanks!
