### ISSUE TITLE
Ruby 2.7.1 Warnings

### ISSUE THREAD

**Issue by l33z3r** [sds/mock_redis#183]
Hi guys, not sure if this is an actual issue, but I get the following warnings when running the gem with Ruby 2.7.1

/Users/coding/.rvm/gems/ruby-2.7.1@whitelabel/gems/mock_redis-0.22.0/lib/mock_redis/zset_methods.rb:29: warning: deprecated Object#=~ is called on Float; it always returns nil

Anyone any ideas?

**Comment by sds** [comment]
This was fixed in #177, but hasn't been released. 

Released [0.23.0](https://github.com/sds/mock_redis/releases/tag/v0.23.0) with the fix.

**Comment by l33z3r** [comment]
Great, thank you 😄
