### ISSUE TITLE
exists returns boolean instead of integer

### ISSUE THREAD

**Issue by jasonatball** [sds/mock_redis#187]
According to Redis documentation for [exists](https://redis.io/commands/exists):
```
Return value
Integer reply, specifically:

1 if the key exists.
0 if the key does not exist.
```

**Comment by sds** [comment]
Thanks for reporting this issue!

Would welcome a pull request fixing. Thank you!

**Comment by jasonatball** [comment]
It looks like going to redis 4.2 changed a lot of the API return values. Is anyone else working this?

**Comment by jasonatball** [comment]
I addressed all existing issues running against the latest redis (4.2.1). Ran into an error message on xadd that didn't seem to be consistent from my setup to the Travis build so I documented it and made Travis happy. Please take a look at the PR.
