### ISSUE TITLE
SCAN fails if keys are deleted in the iteration

### ISSUE THREAD

**Issue by arvid220u** [sds/mock_redis#193]
The following minimal example showcases a discrepancy between MockRedis and the real Redis.

First, let's add two keys:
```ruby
mock_redis = MockRedis.new
mock_redis.set("key1", "value1")
mock_redis.set("key2", "value2")
```

Second, let's scan:
```ruby
mock_redis.scan("0", count: 1)
=> ["1", ["key1"]]
```

This is the expected return value. Now, let's say we want to remove `key1` and continue our scan:
```ruby
mock_redis.del("key1")
mock_redis.scan("1", count: 1)
=> ["0", []]
```

This is where the bug is, because we expect to receive back `["0", ["key2"]]`, which is what the real Redis gives us.

I looked into the [implementation of `scan` in `MockRedis`](https://github.com/sds/mock_redis/blob/094f0d77a9830ab0b124a9667822bf6199943736/lib/mock_redis/utility_methods.rb#L26) and it looks like it behaves quite differently from `scan` in the real Redis, so I'm not sure how to fix it.

I know that `scan` is not listed under the [supported features of `MockRedis`](https://github.com/sds/mock_redis#supported-features), so I totally understand if this is a non-fix. In that case, maybe `scan` should be listed under "Mostly-Supported Commands" of the Readme?

**Comment by sds** [comment]
@alfonsojimenez implemented this long ago (thank you!)

Would love to see a pull request resolving the functional discrepancy—but otherwise agree a documentation change would help clarify.

**Comment by sds** [comment]
Open to pull requests addressing this.
