### ISSUE TITLE
Keys are not consistently converted to strings

### ISSUE THREAD

**Issue by clemens** [sds/mock_redis#217]
Follow-up of #170.

The issue mentioned there also applies to other data types:

- sets
- sorted sets
- lists
- partially strings (e.g. `incr`, `incrby`, `decr`, `decrby`)
- presumably streams (haven't tested it, but the code looks like it)

Reproducible like so:

``` ruby
# assuming REDIS is an instance of MockRedis
irb(main):001:0> REDIS.sadd(:foo, [1, 2])
=> 2
irb(main):002:0> REDIS.zadd(:bar, [1, 2])
=> 1
irb(main):003:0> REDIS.keys
=> [:foo, :bar]
irb(main):004:0> REDIS.flushdb
=> "OK"
irb(main):005:0> REDIS.keys
=> [:foo, :bar]
```

It seems that pretty much everything except hashes (which were fixed in #173) and `set` are broken this way.

Proposed solution:

- extract a `convert(key)` utility method and wrap each usage of keys
- add a separate spec file that test each supported method with string and symbol keys OR add example to each single file

**Comment by sds** [comment]
Open to a pull request addressing this issue.
