### ISSUE TITLE
Moneta 1.5 support

### ISSUE THREAD

**Issue by TomK32** [sds/mock_redis#241]
Currently broken, didn't test with 1.4 but apparently that's working fine. According to the 1.5.0 release notes plenty of work on the adapters hence the error `Adapter must be a Moneta store` I get from moneta isn't suprising.

To be an acceptable adapter, MockRedis might have to respond to `store` and `load` [like the official Redis adapter does](https://www.rubydoc.info/gems/moneta/Moneta/Adapters/Redis).

```
     # /home/tomk32/.rvm/gems/ruby-2.7.5/gems/moneta-1.5.1/lib/moneta/builder.rb:56:in `adapter'
     # /home/tomk32/.rvm/gems/ruby-2.7.5/gems/moneta-1.5.1/lib/moneta.rb:153:in `block in new'
     # /home/tomk32/.rvm/gems/ruby-2.7.5/gems/moneta-1.5.1/lib/moneta/builder.rb:9:in `instance_eval'
     # /home/tomk32/.rvm/gems/ruby-2.7.5/gems/moneta-1.5.1/lib/moneta/builder.rb:9:in `initialize'
     # /home/tomk32/.rvm/gems/ruby-2.7.5/gems/moneta-1.5.1/lib/moneta.rb:170:in `new'
     # /home/tomk32/.rvm/gems/ruby-2.7.5/gems/moneta-1.5.1/lib/moneta.rb:170:in `build'
     # /home/tomk32/.rvm/gems/ruby-2.7.5/gems/moneta-1.5.1/lib/moneta.rb:148:in `new'

```

**Comment by sds** [comment]
Won't be looking into this personally, but feel free to submit a PR adding support if desired.
