### ISSUE TITLE
Incompatible with the new 'redis-client' gem

### ISSUE THREAD

**Issue by suzumejakku** [sds/mock_redis#253]
Hi,

First of all, thanks for this gem which I have used extensively for testing my app.

I recently needed to move to Sideqik 7, the latter needing Redis 6+. Unfortunately, the gem 'redis-rb' does not work with Redis 6+, at least for now. Instead, the authors have created a new gem called 'redis-client' (which is not backward compatible with Redis 5). 

The big change is that redis-client is a thin client and does not mirror directly the calls to Redis. What I mean is that you cannot use redis.set / redis.get / etc, but have to use redis.call("SET", ...) / redis.call("GET", ...). 

Is there any chance that you will provide an updated version of mock_redis which would mimic that behaviour ?

**Comment by sds** [comment]
Hey @suzumejakku, can you clarify what you mean by `redis-rb` not supporting Redis 6+? 

The existing tests are run against Redis 6.2 (see [test suite output](https://github.com/sds/mock_redis/actions/runs/3710407847/jobs/6289899548)), so I'm not sure where the claim that `redis-rb` doesn't support Redis 6 is coming from.

If I'm misunderstanding your comment, appreciate any clarity you can provide. Thanks.

**Comment by suzumejakku** [comment]
Hi @sds,
Sorry, I think this was a poor choice of words on my part.

I think the following blog post from Mike Perham will explain better: 

https://www.mikeperham.com/2022/10/27/introducing-sidekiq-7.0/

In particular, under the "Requirements" paragraph:

> Sidekiq 7.0 now requires Redis 6.2+. That’s a huge jump from 4.0 to 6.2 but Redis Labs has made a lot of changes to Redis commands recently and v6.2 is really necessary to start using the new commands. In 7.1, I’ll update Sidekiq to use those new commands.

> I also worked with @_byroot to migrate Sidekiq to the `redis-client` gem which uses the new [RESP3 protocol](https://github.com/antirez/RESP3/blob/master/spec.md) found in Redis 6.0+. The newer protocol provides precise data types for responses, meaning the Ruby client code is greatly simplified. There are a few compatibility issues between the old and new client; test carefully if you use Sidekiq.redis in your code.

The new `redis-client` gem does not mirror the calls to Redis as it used to with the `redis-rb` gem. On my side, I had to move to `redis-client` to be able to use Sidekiq 7, and when testing with mock_redis, it did not work anymore - due, I suppose, to the changes between `redis-rb` and `redis-client` (as explained in my previous post).

**Comment by matteo95g** [comment]
Hi @suzumejakku, I'm facing the same issue as you after updating to sidekiq 7.0. Were you able to solve it? Thanks

**Comment by suzumejakku** [comment]
Hi @matteo95g,
No, I think we simply cannot use mock_redis as it is today, because of this RESP3 protocol. We'll have to wait on @sds.

By the way, nothing to do with mock_redis but I had to revert back to Sidekiq 6 because the Redis I use on Heroku (where I host my app) does not implement RESP3 yet :-/

Anyway, RESP3 seems to be the future, so let's wait on @sds.

**Comment by sds** [comment]
Thanks for clarifying. 

I'm not personally investing time to migrate to supporting `redis-client`, but would happily merge a PR. 

It's not entirely clear to me what the scope of such a change would be, so I will defer to someone more familiar to make an assessment and determine if migrating MockRedis to the `redis-client` gem is worthwhile, or if there are other solutions more convenient/appropriate.

**Comment by pbstriker38** [comment]
Maintainer of `redis-client` does not recommend mocking. But it could be done by implementing a "test" driver.

https://github.com/redis-rb/redis-client/issues/68

**Comment by guilleiguaran** [comment]
The changes required to migrate to redis-client seem to require a big rewrite in the mocking libraries.

Perhaps the maintainer of the library is right on this and it doesn't worth investing a significant amount of time migrating the mocking libraries to use redis-client nowadays when running Redis is widespread in all CI servers and running it locally is easier than many years ago when the mocking projects started thanks to tools like Docker and Homebrew.

**Comment by sds** [comment]
No plans to implement this, but open to a pull request.
