### ISSUE TITLE
Add #sadd? to match redis-rb v4.8.0

### ISSUE THREAD

**Issue by 17jmumford** [sds/mock_redis#267]
Redis-rb added a new method to their set methods called #sadd? which returns a boolean instead of an integer like #sadd. They also added a warning that sends a message to the console every time a user hits the old #sadd method. This is unique to the ruby client of Redis, and cannot be found in the general Redis documentation. 
[#sadd? in redis-rb Github](https://github.com/redis/redis-rb/blob/master/lib/redis/commands/sets.rb)
[Redis-rb changelog](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md)

This new feature will need to be added to mock_redis so that as users update their codebase to match redis-rb, their unit tests will reflect that update.

**Comment by thushw** [comment]
@sds -- I added a PR to fix this, there was one more issue I addressed, which was that it seems zadd changed slightly to accept an empty array in the newer redis. (this might be missing in the PR from @groeneman) please let me know how I can help further. We use redis extensively and this will help us a lot!
