### ISSUE TITLE
TypeError when using `eval()`

### ISSUE THREAD

**Issue by timobleeker** [sds/mock_redis#276]
Hello! 

I can see that the `eval` implementation of mock_redis does not do anything: https://github.com/sds/mock_redis/blob/f4a151d3724d7c7f8e084535c18d7191cfed6d0c/lib/mock_redis/database.rb#L281

But I do get a (for me) surprising error when running my tests on a piece of code that uses `eval`

Rspec fails with a TypeError:

```
     TypeError:
       wrong argument type Hash (expected binding)
```

Is this an issue in `mock_redis`, or in my understanding? 😄

**Comment by sds** [comment]
The README mentions in the [Unsupported Commands](https://github.com/sds/mock_redis#unsupported-commands) section that `eval` isn't supported. The error here is odd, but at the end of the day we don't support `eval`.

Would welcome a PR with any improvement.
