### ISSUE TITLE
Add :exat and :pxat keywords to #set method

### ISSUE THREAD

**Issue by jcagarcia** [sds/mock_redis#279]
The #set method has a :exat and :pxat keywords to set the expiration time in Unix time format in seconds and milliseconds (see https://www.rubydoc.info/gems/redis/Redis/Commands/Strings#set-instance_method). MockRedis is returning an ArgumentError: unknown keyword: :exat when using that keyword.

**Comment by sds** [comment]
Implemented in #280. Thank you.
