### ISSUE TITLE
From redis-rb 5.0.0, `sadd` and `srem` always return integers

### ISSUE THREAD

**Issue by mikevoets** [sds/mock_redis#281]
In this gem it still returns `true` or `false`. This has changed from `redis-rb` version 5, see https://github.com/redis/redis-rb/blob/master/CHANGELOG.md.

As a workaround, I started using `sadd?` and `srem?` to align the behaviour of this gem and `redis-rb`.

**Comment by sds** [comment]
Thanks for the research and providing a workaround!

I'm supportive of dropping support for older Redis gem versions as part of fixing in the project itself. At some point the ecosystem needs to move forward.
