### ISSUE TITLE
Support for `redis-client`

### ISSUE THREAD

**Issue by MarkSiemers-msr** [sds/mock_redis#303]
With Sidekiq 7.0, they have moved from `redis-rb` to `redis-client` which seems to have a different class/namespace of `RedisClient` (as compared to `Redis`).

Do you have any plans to support mocks for this gem/namespace (redis-client)?

Thank you

References:
https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-Upgrade.md#redis-client
https://github.com/redis-rb/redis-client?tab=readme-ov-file#usage

**Comment by sds** [comment]
See #253. No plans to implement, but open to a pull request!
